# Generated by Django 3.0.8 on 2020-12-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
